Add HPX tests
E4S-Project/testsuite pull request #16
Opened 2021-11-05 17:52 UTC by msimberg

This adds tests for HPX: two plain CPU-only single-node smoke tests, one GPU test for CUDA and HIP, and one distributed test.

I was able to run these successfully locally, but is there any way to check that this is going to succeed on whatever system it will be run on? I currently require nothing special from the hpx spec, and e.g. the GPU test compiles to an empty test if HPX doesn't have `+cuda` or `+rocm` in the spec. The distributed test should run with with any parcelport (the `networking` variant), assuming it's launched appropriately. `networking=none` would not work. Can I assume that the spec will always not be `networking=none` (`tcp` is the default)?

2021-11-15 23:03 UTC, wspear requested changes
Since there is a minimum cmake version which may not be in the environment by default I suggest adding `spackLoadUnique cmake@3.17:` to compile.sh

The success/failure of a test phase is determined by the return value of the script. Since run.sh concludes with a diff between two differing files (I assume they are supposed to differ, they do in my test run), which returns 1, the run phase is registered as a failure. You can catch the return code and process it in the script (to confirm that the files differ) or conclude the script with a different command to work around this.

2021-11-16 09:07 UTC, msimberg commented
Thanks for having a look!

> Since there is a minimum cmake version which may not be in the environment by default I suggest adding `spackLoadUnique cmake@3.17:` to compile.sh

Will do.

> The success/failure of a test phase is determined by the return value of the script. Since run.sh concludes with a diff between two differing files (I assume they are supposed to differ, they do in my test run), which returns 1, the run phase is registered as a failure. You can catch the return code and process it in the script (to confirm that the files differ) or conclude the script with a different command to work around this.

Since the script runs with `bash -e` this should be fine. The individual tests exit with a non-zero exit code if they fail, and the since the files should _not_ differ the exit code of `diff` is also fine.

What does does the diff (or the reference/actual output files) show? Is there any way for me to debug this myself (other than on my own machine)?

2021-11-16 09:28 UTC, msimberg commented
> Thanks for having a look!
> 
> > Since there is a minimum cmake version which may not be in the environment by default I suggest adding `spackLoadUnique cmake@3.17:` to compile.sh
> 
> Will do.
> 
> > The success/failure of a test phase is determined by the return value of the script. Since run.sh concludes with a diff between two differing files (I assume they are supposed to differ, they do in my test run), which returns 1, the run phase is registered as a failure. You can catch the return code and process it in the script (to confirm that the files differ) or conclude the script with a different command to work around this.
> 
> Since the script runs with `bash -e` this should be fine. The individual tests exit with a non-zero exit code if they fail, and the since the files should _not_ differ the exit code of `diff` is also fine.
> 
> What does does the diff (or the reference/actual output files) show? Is there any way for me to debug this myself (other than on my own machine)?

2021-11-16 09:28 UTC, msimberg commented
Sorry, clicking the wrong buttons.

2021-11-16 15:00 UTC, wspear commented
Ah, I see! Here is the run output from my Ubuntu workstation. If you know of a quick fix we can go with that. Otherwise I can try some additional testing or digging on my side to help figure out what's happening or I can try to reproduce it on a system where we both have access.

```
wspear@yu:~/Code/testsuite/validation_tests/hpx$ cat run.log
Skipping load: Environment already setup
+ mpirun -np 1 ./build/test_future --hpx:use-process-mask
+ mpirun -np 1 ./build/test_algorithm --hpx:use-process-mask
+ mpirun -np 1 ./build/test_gpu --hpx:use-process-mask
skipping HPX GPU test, CUDA/HIP support not available
+ mpirun -np 8 ./build/test_distributed --hpx:use-process-mask
+ sort test_distributed.log
+ rm -f test_distributed_reference.log
++ seq 0 7
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 0'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 1'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 2'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 3'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 4'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 5'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 6'
+ for i in $(seq 0 $((TEST_RUN_PROCARG - 1)))
+ echo 'Hello world from locality 7'
+ diff test_distributed_sorted.log test_distributed_reference.log
2,8c2,8
< Hello world from locality 0
< Hello world from locality 0
< Hello world from locality 0
< Hello world from locality 0
< Hello world from locality 0
< Hello world from locality 0
< Hello world from locality 0
---
> Hello world from locality 1
> Hello world from locality 2
> Hello world from locality 3
> Hello world from locality 4
> Hello world from locality 5
> Hello world from locality 6
> Hello world from locality 7
```

2021-11-17 09:05 UTC, msimberg commented
Thanks @wspear for the log!

I can think of two things that go wrong:
1. The spack package that was loaded does not have `networking=mpi` (since you're running with `mpirun`). Could you check the full spec of the package that you have loaded? Can we assume that `TEST_RUN_CMD` will always initialize MPI (whether it's through some batch system, or through plain `mpirun`)? If yes, I would probably simply require `networking=mpi` for the spec. `networking=tcp` is mostly for testing and debugging anyway.
2. HPX does not recognize the MPI environment variables as an MPI environment. We have a default list of variables to look for. This can also be customized at runtime to help HPX detect the environment. Could you post the environment variables inside `mpirun` (or at least the subset of MPI-related variables)?

2021-11-17 15:30 UTC, wspear commented
If the setup script does `spackLoadUnique hpx networking=mpi` (and I build hpx with mpi) it works. Is it reasonable to use that in the setup script? It will say the required spack package is not found if only networking=tcp, or any other option but mpi is available. If that might that exclude other variants that would work and you would want to test a little more logic might be needed to specifically exclude networking=tcp.

2021-11-18 09:08 UTC, msimberg commented
I think requiring `networking=mpi` is very reasonable from the HPX perspective as long as it's not a problem for any test setups that you have. It's what everyone should be using in production anyway, so it makes sense to test that case. I'll make that change for now, and you can comment later if it would actually be useful to test non-MPI builds.

2021-11-18 19:37 UTC, wspear commented
Note that the spec for hpx in e4s 21.11 doesn't specify networking=mpi so we will probably need to update that. There is also an `hpx +cuda` variant for systems where cuda is supported. Is it more appropriate to specify `hpx +cuda networking=mpi` ?

2021-11-18 19:37 UTC, merged

2021-11-22 08:43 UTC, msimberg commented
> Note that the spec for hpx in e4s 21.11 doesn't specify networking=mpi so we will probably need to update that. There is also an `hpx +cuda` variant for systems where cuda is supported. Is it more appropriate to specify `hpx +cuda networking=mpi` ?

Currently the tests will handle both `+cuda` and `~cuda`. Will all test systems have CUDA available? If not, I'd leave it out and just test whatever is available.

2023-06-16 21:41 UTC, wspear commented
Hi @msimberg . We're having build errors for this test with HPC 1.9.0. I'm guessing the API has changed so I was looking for equivalent test code from that version but couldn't find these source files or anything in the source tree that I was confident had the same coverage. Would you be willing to take a look?

`[ 62%] Building CXX object CMakeFiles/test_distributed.dir/test_distributed.cpp.o
/home/wspear/testsuite/validation_tests/hpx/test_distributed.cpp:25:28: warning: 'id_type' is deprecated: hpx::naming::id_type is deprecated, use hpx::id_type instead (This functionality is deprecated starting HPX V1.8 and will be removed in the future. You can define HPX_HAVE_DEPRECATION_WARNINGS_V1_8=0 to acknowledge that you have received this warning.) [-Wdeprecated-declarations]
  std::vector<hpx::naming::id_type> localities = hpx::find_all_localities();
                           ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/naming_base/id_type.hpp:418:19: note: 'id_type' has been explicitly marked deprecated here
    using id_type HPX_DEPRECATED_V(
                  ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/config/deprecation.hpp:75:5: note: expanded from macro 'HPX_DEPRECATED_V'
    HPX_PP_CAT(HPX_PP_CAT(HPX_PP_CAT(HPX_DEPRECATED_V, major), _), minor)(x)
    ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/preprocessor/cat.hpp:28:26: note: expanded from macro 'HPX_PP_CAT'
#define HPX_PP_CAT(a, b) HPX_PP_CAT_I(a, b)
                         ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/preprocessor/cat.hpp:36:28: note: expanded from macro 'HPX_PP_CAT_I'
#define HPX_PP_CAT_I(a, b) a##b
                           ^
<scratch space>:133:1: note: expanded from here
HPX_DEPRECATED_V1_8
^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/config/deprecation.hpp:27:7: note: expanded from macro 'HPX_DEPRECATED_V1_8'
    [[deprecated(x " (" HPX_PP_EXPAND(HPX_DEPRECATED_MSG_V1_8) ")")]]
      ^
/home/wspear/testsuite/validation_tests/hpx/test_distributed.cpp:25:55: error: no member named 'find_all_localities' in namespace 'hpx'
  std::vector<hpx::naming::id_type> localities = hpx::find_all_localities();
                                                 ~~~~~^
/home/wspear/testsuite/validation_tests/hpx/test_distributed.cpp:29:21: warning: 'id_type' is deprecated: hpx::naming::id_type is deprecated, use hpx::id_type instead (This functionality is deprecated starting HPX V1.8 and will be removed in the future. You can define HPX_HAVE_DEPRECATION_WARNINGS_V1_8=0 to acknowledge that you have received this warning.) [-Wdeprecated-declarations]
  for (hpx::naming::id_type const &locality : localities) {
                    ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/naming_base/id_type.hpp:418:19: note: 'id_type' has been explicitly marked deprecated here
    using id_type HPX_DEPRECATED_V(
                  ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/config/deprecation.hpp:75:5: note: expanded from macro 'HPX_DEPRECATED_V'
    HPX_PP_CAT(HPX_PP_CAT(HPX_PP_CAT(HPX_DEPRECATED_V, major), _), minor)(x)
    ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/preprocessor/cat.hpp:28:26: note: expanded from macro 'HPX_PP_CAT'
#define HPX_PP_CAT(a, b) HPX_PP_CAT_I(a, b)
                         ^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/preprocessor/cat.hpp:36:28: note: expanded from macro 'HPX_PP_CAT_I'
#define HPX_PP_CAT_I(a, b) a##b
                           ^
<scratch space>:133:1: note: expanded from here
HPX_DEPRECATED_V1_8
^
/lus/gila/projects/CSC250STPM01_CNDA/E4S/23.05/spack/opt/spack/linux-sles15-icelake/oneapi-2023.1.0/hpx-1.9.0-ys44eu3rd5mocxp2g5moae6xbkera4zt/include/hpx/config/deprecation.hpp:27:7: note: expanded from macro 'HPX_DEPRECATED_V1_8'
    [[deprecated(x " (" HPX_PP_EXPAND(HPX_DEPRECATED_MSG_V1_8) ")")]]
      ^
2 warnings and 1 error generated.`

2023-06-18 23:07 UTC, hkaiser commented
I will have a look.